### PR TITLE
Ready to get my component merged into the mainline code!

### PR DESCRIPTION
**Pull request by stephfrankable**

### CODE REVIEW

**Comment by tsteelematc** [comment]
We gave you some merge conflicts to resolve in the PR branch : - )

Should be just like the conflicts I resolved in the vids.

Once resolved, I can accept/merge your PR. Thanks.

**Comment by stephfrankable** [comment]
I believe my conflicts have been resolved!  :) Thank you!

**Comment by tsteelematc** [comment]
You resolved the conflicts, but did you test it locally before pushing to your PR branch?

Looks like you have a TS error in the PR...

image

**Comment by tsteelematc** [comment]
And please make sure your component is at the bottom of the page... Thanks...

**Comment by stephfrankable** [comment]
There we go!  I moved my component to the bottom of the page and resolved my TS error - definitely forgot the "test locally" step the first time.  Thank you!  :)

**Comment by tsteelematc** [comment]
Right on. Perfect class experience to remind you of working below the line then pushing above the line. Good job. And you won merge-chicken against @EmeraldPangolin, nothing personal, just took them in PR # order. Thanks.

**Pull request merged**
