### PR TITLE
Request to get my math component added into the main code line.

### PR DESCRIPTION
**Pull request by arice-student**

### CODE REVIEW

**Comment by arice-student** [comment]
Here is my pull request for my week 07 slack n tell.

**Comment by annamccreery** [comment]
I'm sorry for messing in here!!! I completely thought I was in my branch since I had the same comment from Tom. I reset it to be active.

**Comment by tsteelematc** [comment]
@arice-student 

Please put my component, back above yours. The whole idea is that we ultimately want everybody's component in the running app.

image

**Comment by arice-student** [comment]
I just added the <app-tjs-multiplication> tags back to the file and pushed it back into GitHub.

**Comment by tsteelematc** [comment]
Can you move your component to the bottom? Then I can accept this PR. Thanks.

**Pull request merged**
